#!/bin/sh

cd "${0%/*}"
rm -rf *.png

# single-image launch screen
curl -o Default@2x~universal~anyany.png https://via.placeholder.com/2732.png

# multi-image launch screen
curl -o Default@2x~iphone~anyany.png https://via.placeholder.com/1334.png
curl -o Default@2x~iphone~comany.png https://via.placeholder.com/750x1334.png
curl -o Default@2x~iphone~comcom.png https://via.placeholder.com/1334x750.png
curl -o Default@3x~iphone~anyany.png https://via.placeholder.com/2208x2208.png
curl -o Default@3x~iphone~anycom.png https://via.placeholder.com/2208x1242.png
curl -o Default@3x~iphone~comany.png https://via.placeholder.com/1242x2208.png
curl -o Default@2x~ipad~anyany.png https://via.placeholder.com/2732x2732.png
curl -o Default@2x~ipad~comany.png https://via.placeholder.com/1278x2732.png
